### ISSUE TITLE
Deprecations are displayed even if there are no ignore rules in composer.json

### ISSUE THREAD

**Issue by mxr576** [mxr576/ddqg-composer-audit#19]
Follow up on https://github.com/mxr576/ddqg-composer-audit/commit/49fbb55215575d7caece0217b2baac19698611aa

**Comment by jurgenhaas** [comment]
Not sure if my issue belongs here, but it feels pretty close.

I'm using composer 2.7 and ddqg-composer-audit 1.1

In my composer.json I'm using the audit ignore config from composer and I'm listing all the accepted alpha and beta release "CVEs" in there. This is working just as expected.

Only if a project also uses a deprecated package, which is also listed in audit ignore, I'm getting the deprecation notice:

```
Deprecation Notice: Since 1.1.0 DDQG Composer Audit plugin's ignore features are deprecated, use Composer's built-in audit ignore feature instead. https://getcomposer.org/doc/06-config.md#ignore in /drupal/vendor/mxr576/ddqg-composer-audit/src/Domain/PackageIgnore/PackageIgnoreRuleOptimizer.php:33
```

Am I misunderstanding something, or is this a wrong behaviour?

**Comment by mxr576** [comment]
This is an expected behavior, this plugin's [own ignore feature ](https://github.com/mxr576/ddqg-composer-audit/issues/7)- that was introduced sooner than Composer Audit's ignore feature - became deprecated in 1.1.0. These messages warns you and others to change the way how you ignore packages.
The deprecation message was added in a traditional PHP/Composer way :tm:  and it is displayed on STDERR, if you do not want to see that somewhere, ignore output on STDERR (`2>/dev/null`).

**Comment by jurgenhaas** [comment]
Now, this is confusing since I'm only using the composer audit ignore, and nothing else. That's why I'm wondering that I still get the deprecation message.

**Comment by mxr576** [comment]
Meh... you are right. I found the root cause and I'll address it shortly.

**Comment by mxr576** [comment]
Should be fixed, please check.
https://github.com/mxr576/ddqg-composer-audit/compare/1.1.0...1.1.1

**Comment by jurgenhaas** [comment]
Confirmed, the deprecation warning is now gone. Thank you very much for the quick turnaround.

**Comment by mxr576** [comment]
I am glad to hear that and sorry for the noise. I am planning to further improve the automated test coverage suite of all my Composer plugins, so it will become much easier covering non-happy paths (like this deprecation display story) as well.

**Comment by jurgenhaas** [comment]
Thank you so much for your great work on this. We've just integrated this plugin into our pipelines and become really strict about what is allowed to go through and what not. Another step for better sleep ;-)
