### ISSUE TITLE
Allow PHP 8.3 in the version constraint

### ISSUE THREAD

**Issue by jurgenhaas** [mxr576/ddqg-composer-audit#21]
Since Drupal 11 has PHP 8.3 as a minimum requirement, we're starting to test with PHP 8.3 but unfortunately it doesn't allow us to install that since the constraint is bound to `~8.1.0 || ~8.2.0`

Could you please allow for 8.3 as well?

**Comment by mxr576** [comment]
I'll take a look as soon as I can, until this is resolved I can recommend `COMPOSER_IGNORE_PLATFORM_REQ=php+`.

https://getcomposer.org/doc/03-cli.md#composer-ignore-platform-req-or-composer-ignore-platform-reqs

**Comment by jurgenhaas** [comment]
Thanks @mxr576 for looking into this. I can confirm that the workaround to ignore platform requirements does work OK for the time being.

**Comment by mxr576** [comment]
Closed via https://github.com/mxr576/ddqg-composer-audit/commit/facb45b5ac03c3cc4e51fd4b73182cec5b850ff6.

It could have been a bit easier... :grimacing: 

https://github.com/mxr576/ddqg-composer-audit/compare/1.1.1...1.2.0

1.2.0 is out! Happy testing!

**Comment by jurgenhaas** [comment]
Confirmed, this is working great. Kudos for an outstanding maintainership. Sorry to hear it was more work than expected.

**Comment by mxr576** [comment]
Well, it is not a problem at all, the test suite became more stable as it was before.
